name: Descargar archivo y redeploy

on:
  schedule:
    - cron: '0 0 */21 * *'  # cada 15 días (ajustá a tu gusto)
  workflow_dispatch:       # para ejecutarla manualmente desde GitHub

jobs:
  update-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
      
        run: pip install -r requirements.txt 
      - name: Instalar navegadores Playwright
        run: python -m playwright install
        
      - name: Obtener nueva versión desde Python
        id: get_version
        run: echo "VERSION=$(python src/utils/version.py)" >> $GITHUB_OUTPUT

      - name: Actualizar VERSION env en Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Nuevo valor: $VERSION"

          curl -X PATCH "https://api.vercel.com/v9/projects/prj_D6NMjIiBXKBiaG1oFqWdfKw0pMq0/env" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "key": "VERSION",
              "value": "'"$VERSION"'",
              "target": ["production", "preview"]
            }'
      - name: Descargar archivos
        env:
          VIDEO_URL: ${{ secrets.PUBLIC_VIDEO_URL }}
          POSTER_URL: ${{ secrets.PUBLIC_POSTER_URL }}
        run: |
          mkdir -p public/assets
          curl -L "$VIDEO_URL" -o public/assets/bg-video.mp4
          curl -L "$POSTER_URL" -o public/assets/bg-poster.webp

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions"
          git config user.email "bot@example.com"
          git add public/assets/bg-video.mp4 public/assets/bg-poster.webp
          git commit -m "Actualización automática del video" || echo "No hay cambios"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master



