name: Descargar archivo y redeploy

on:
  schedule:
    - cron: '0 0 */21 * *'  # cada 15 días (ajustá a tu gusto)
  workflow_dispatch:       # para ejecutarla manualmente desde GitHub

jobs:
  update-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
      
        run: pip install -r requirements.txt 
      - name: Instalar navegadores Playwright
        run: python -m playwright install
        
      - name: Ejecutar scraping y actualizar código
        run: python src/utils/version.py

      - name: Descargar archivos
        env:
          VIDEO_URL: ${{ secrets.PUBLIC_VIDEO_URL }}
          POSTER_URL: ${{ secrets.PUBLIC_POSTER_URL }}
        run: |
          mkdir -p public/assets
          curl -L "$VIDEO_URL" -o public/assets/bg-video.mp4
          curl -L "$POSTER_URL" -o public/assets/poster.webp

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions"
          git config user.email "bot@example.com"
          git add public/assets/video.mp4
          git commit -m "Actualización automática del video" || echo "No hay cambios"
          git push
