name: Descargar archivo y redeploy

on:
  schedule:
    - cron: '0 0 */21 * *'  # cada 15 días (ajustá a tu gusto)
  workflow_dispatch:       # para ejecutarla manualmente desde GitHub

jobs:
  update-asset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        run: pip install -r requirements.txt 

      - name: Ejecutar scraping y actualizar código
        run: python src/utils/version.py

      - name: Descargar archivo
        env:
          URL: ${{ secrets.ASSET_URL }}
        run: |
          mkdir -p public/assets
          curl -L  $URL -o public/assets/video.mp4

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions"
          git config user.email "bot@example.com"
          git add public/assets/video.mp4
          git commit -m "Actualización automática del video" || echo "No hay cambios"
          git push
